# -----------------------------
#       ORewards V2.0         /
#   github.com/rootDeibis     \
#                             /
#  By: rootDeibis Developer   \
# -----------------------------



database:
  type: "SQLFile" # Available Types: SQLFile and MYSQL
  #host: "127.0.0.1"
  #credentials:
    #username: "root"
    #password: "password_here"
    #databaseName: "orewards"

categories-gui:
  title: "&aORewards &7> &aCategories"
  rows: 9

categories:
  default:
    item:
      material: "STONE"
      slot: 10
      displayname: "&aDefault Rewards"
      lore:
        - "&dClick to open"

